### ISSUE TITLE
Faster Implicit update

### ISSUE THREAD

**Issue by jdonners** [PhysicsofFluids/AFiD#5]
Massimiliano Fatica (NVIDIA) wrote:

While I was adding the GPU path to  the Implicit update routines, I found a good improvement  (2x-3x) for the CPU code with a better use of the dgttrs call.

Basically, after the dgttrf call, instead of solving each vertical line:

```FORTRAN
       do ic=xstart(3),xend(3)
       do jc=xstart(2),xend(2)

!     Normalize RHS of equation

        fkl(1)= real(0.,fp_kind)
        do kc=2,nxm
         ackl_b=real(1.0,fp_kind)/(real(1.0,fp_kind)-ac3ssk(kc)*betadx)
         fkl(kc)=rhs(kc,jc,ic)*ackl_b
        end do
        fkl(nx)= real(0.,fp_kind)

!     Solve equation using LAPACK library

        call dgttrs('N',nx,1,amkT,ackT,apkT,appk,ipkv,fkl,nx,info)

!      Update temperature field

        do kc=2,nxm
          temp(kc,jc,ic) = temp(kc,jc,ic) + fkl(kc)
        end do

       enddo
      end do
```
you can solve all of them together

```FORTRAN
       nrhs=(xend(3)-xstart(3)+1)*(xend(2)-xstart(2)+1)
! Normalize RHS (but this should be moved in the main loop of the corresponding ImplicitUpdate
       do ic=xstart(3),xend(3)
         do jc=xstart(2),xend(2)
            do kc=2,nxm
              ackl_b=real(1.0,fp_kind)/(real(1.0,fp_kind)-ac3ssk(kc)*betadx)
              rhs(kc,jc,ic)=rhs(kc,jc,ic)*ackl_b
             end do
          end do
      end do

      call dgttrs('N',nx,nrhs,amkT,ackT,apkT,appk,ipkv,rhs,nx,info)
      
! You can also add OpenMP directives on these loops
       do ic=xstart(3),xend(3)
         do jc=xstart(2),xend(2)
            do kc=2,nxm
              temp(kc,jc,ic)=temp(kc,jc,ic) + rhs(kc,jc,ic)
             end do
          end do
      end do
```

**Comment by jdonners** [comment]
R wrote:
* test on 384^3 using  ./configure FCFLAGS="-O3 -xAVX -axCORE-AVX2”. This version of the code crashes on an Ivy Bridge node (i.e. AVX) with the message “too large local residue for mass conservation at:”. This code works fine on a Haswell node (i.e. AVX2).
* Using only the “-O3” flag everything works well on both types of nodes.
* Using the “-O3 -xAVX” flags the code fails on both types of nodes, so the problem is in the part “-xAVX”.

It also occurs with the latest compiler version (16.0.1).

**Comment by jdonners** [comment]
some print statements show:
```
...
16:  dmax,resid=  6.953275390687991E-310  1.000000000000000E-002
18:  dmax,resid=  6.952658331733957E-310  1.000000000000000E-002
00:  dmax,resid= -1.797693134862316E+308  1.000000000000000E-002
00:           too large local residue for mass conservation at:
```
only process 0 has a somewhat excessive residue..

**Comment by jdonners** [comment]
the same happens with ./configure FCFLAGS="-xAVX -O0 -g -traceback", so without optimization.

**Comment by stevensrjam** [comment]
Committed in commit 294.
