### ISSUE TITLE
Inconsistent initialization of temperature

### ISSUE THREAD

**Issue by maxcuda** [PhysicsofFluids/AFiD#8]
In CreateInitialConditions.F90, the temperature is initialized as:

do i=xstart(3),xend(3)
      do j=xstart(2),xend(2)
      do k=2,nxm
             temp(k,j,i)= tempbp(j,i) - (tempbp(j,i) - temptp(j,i)) &
                         *xc(k)
           enddo
          end do 
        end do
      

        temp(1,:,:)=1.0d0
        temp(nx,:,:)=0.0d0

The last two assignments should use tempbp for k=1 and tempt for k=nx.
I also suggest to pull them in the previous loop, since temp has halo cells.

**Comment by stevensrjam** [comment]
Thank for finding this. I agree that the boundary conditions should be set using  “tempbp" and “tempt”.

I guess we have the following two options

Option 1 
!assign linear temperature profile in the nodes k=2 to k=nxm
do i=xstart(3),xend(3)
do j=xstart(2),xend(2)
do k=2,nxm
temp(k,j,i)=tempbp(j,i)-(tempbp(j,i)-temptp(j,i))*xc(k)
enddo
enddo 
enddo

!assign the boundary conditions at k=1 and k=nx
do ic=xstart(3),xend(3)
do jc=xstart(2),xend(2)
temp(1 ,jc,ic) = tempbp(jc,ic)
temp(nx,jc,ic) = temptp(jc,ic)
end do 
end do 

Probably this should also work in this case

Option 2
!assign linear temperature profile in the nodes k=1 to k=nx
do i=xstart(3),xend(3)
do j=xstart(2),xend(2)
do k=1,nx ! Changed loop boundary to make sure all elements are assigned
temp(k,j,i)=tempbp(j,i)-(tempbp(j,i)-temptp(j,i))*xc(k)
enddo
enddo 
enddo

**Comment by maxcuda** [comment]
In the GPU version, I have implemented the loop as:

  do i=xstart(3),xend(3)
     do j=xstart(2),xend(2)
        do k=2,nxm
           temp(k,j,i)= tempbp(j,i) - (tempbp(j,i) - temptp(j,i)) &
                *xc(k)
        enddo
     end do
        temp(1 ,j,i)=tempbp(j,i)
        temp(nx,j,i)=tempbp(j,i)
  end do


There is another problem. 
xc(nx) is alx3, the linear interpolation should be
temp(k,j,i)=tempbp(j,i)-(tempbp(j,i)-temptp(j,i))*xc(k)/xc(nx)

in case alx3 is not 1.

**Comment by stevensrjam** [comment]
Yes, It should indeed be

xc(k)/xc(nx)

A similar change should be implemented for vx and vy in the loop above as these also do not take the actual size of the domain into account, but also implicitly assume the lengths to be 1.0. The “sin” and “cos” terms in the vx and vy definition should have a pi to get a smooth velocity field as initial condition in the periodic domain.


On Jan 29, 2016, at 23:28, maxcuda <notifications@github.com<mailto:notifications@github.com>> wrote:


In the GPU version, I have implemented the loop as:

do i=xstart(3),xend(3)
do j=xstart(2),xend(2)
do k=2,nxm
temp(k,j,i)= tempbp(j,i) - (tempbp(j,i) - temptp(j,i)) &
*xc(k)
enddo
end do
temp(1 ,j,i)=tempbp(j,i)
temp(nx,j,i)=tempbp(j,i)
end do

There is another problem.
xc(nx) is alx3, the linear interpolation should be
temp(k,j,i)=tempbp(j,i)-(tempbp(j,i)-temptp(j,i))*xc(k)/xc(nx)

in case alx3 is not 1.

**Comment by stevensrjam** [comment]
Initialization of temperature boundary conditions updated in commit 292
